const data = {
  "Shipment_UID": 5592040,
  "S_Year": 2024,
  "Shipment_ID": "SSELS0028387",
  "Trans": "SEA",
  "Customs_Info": "ITN X20240823247428",
  "Mode": "FCL",
  "Origin": "USWER",
  "Origin_Country": "US",
  "Destination": "AEJEA",
  "Destination_Country": "AE",
  "Consignor_Code": "BANNAMORF_LS",
  "Consignor_Name": "BANDAI NAMCO AMERICA",
  "Consignee_Code": "AMUINTJEA_LS",
  "Consignee_Name": "AMUSEMENT SERVICES INTERNATIONAL",
  "House_Ref": "SSELS0028387",
  "INCO": "EXW",
  "Additional_Terms": null,
  "PPD_CCX": "CCX",
  "Goods_Description": null,
  "Origin_ETD": "2024-08-30 00:00:00.000",
  "Destination_ETA": "2024-10-07 19:01:00.000",
  "Weight": 9226.0,
  "Weight_UQ": "LB",
  "Volume": 0.0,
  "Volume_UQ": "M3",
  "Loading_Meters": 0,
  "Chargeable": 4.185,
  "Chargeable_Unit_UQ": "M3",
  "Inner_Packets": 0,
  "Inner_Unit_UQ": "CTN",
  "Outer_Packets": 22,
  "Outers_Unit_UQ": "PKG",
  "Added_Date": "2024-08-21 18:41:00.000",
  "Controlling_Customer_Code": "LSGLOWESJEA3",
  "Controlling_Customer_Name": "GLOBELINK WEST STAR SHIPPING LLC",
  "Controlling_Agent_Code": null,
  "Controlling_Agent_Name": null,
  "Transport_Job": "N",
  "Brokerage_Job": "Y",
  "Is_Master_Lead": "N",
  "Master_Lead_Ref": null,
  "Import_Broker_Code": null,
  "Import_Broker_Name": null,
  "Export_Broker_Code": null,
  "Export_Broker_Name": null,
  "Job_Branch": "LNJ",
  "Job_Dept": "FES",
  "Local_Client_Code": "BANNAMLON_LS",
  "Local_Client_Name": "BANDAI NAMCO AMUSEMENT EUROPE LTD,",
  "Job_Sales_Rep": "5FS/Freehand Shipments",
  "Job_Operator": "5RS/Renjith Soman",
  "Job_Status": "CMP",
  "Job_Opened": "2024-08-21 18:41:00.000",
  "Recognized_Revenue": 1830.0,
  "Recognized_WIP": 0.0,
  "Total_Recognized_Income_REV_WIP": 1830.0,
  "Recognized_Cost": -724.4,
  "Recognized_Accrual": 0.0,
  "Total_Recognized_Expense_CS_ACR": -724.4,
  "Job_Profit": 1105.6,
  "Consol_ID": "CESLS0009366",
  "First_Load": "USWER",
  "Last_Discharge": "AEJEA",
  "ETD_First_Load": "2024-08-30 00:00:00.000",
  "ETA_Last_Discharge": "2024-10-07 15:30:00.000",
  "Master_BL": "242154250",
  "Vessel": "W KYRENIA",
  "Flight_Voyage": "433E",
  "Load_Port": "USWER",
  "Discharge": "AEJEA",
  "ETD_Load": "2024-08-30 00:00:00.000",
  "ETA_Discharge": "2024-10-07 15:30:00.000",
  "Sending_Agent_Code": "LAVAMEINJ_AG",
  "Sending_Agent_Name": "LAVINSTAR AMERICA INC",
  "Receiving_Agent": "LSGLOWESJEA3",
  "Receiving_Agent_Name": "GLOBELINK WEST STAR SHIPPING LLC",
  "Co_loaded_With": null,
  "Co_loader_Name": null,
  "Carrier_Code": "MAELIN_WW",
  "Carrier_Name": "MAERSK LINE A/S",
  "TEU": 2.0,
  "Container_Count": 1.0,
  "Other": null,
  "C20F": null,
  "C20R": null,
  "C20H": null,
  "C40F": null,
  "C40R": null,
  "C40H": 1.0,
  "C45F": null,
  "GEN": null,
  "Service_Level_Code": "STD",
  "Shippers_Reference": null,
  "Consignor_City": "SPRINGFIELD",
  "Consignor_State": "IL",
  "Consignor_Postcode": "62703-4261",
  "Consignee_City": "DUBAI",
  "Consignee_State": null,
  "Consignee_Postcode": null,
  "Consol_ATD": null,
  "Consol_ATA": "Oct  7 2024  4:10PM",
  "Job_Revenue_Recognition_Date": "FAR 29-Aug-24",
  "Direction": "Export",
  "Local_Client_AR_Settlement_Group_Code": null,
  "Local_Client_AR_Settlement_Group_Name": null,
  "Overseas_Agent_Code": "LSGLOWESJEA3",
  "Overseas_Agent_Name": "GLOBELINK WEST STAR SHIPPING LLC",
  "Job_Overseas_Agent_AR_Settlement_Group_Code": null,
  "Job_Overseas_Agent_AR_Settlement_Group_Name": null,
  "Commodity": "General",
  "Contract_No": null,
  "Actual_Cartage_Delivery_Date_Time": null,
  "Actual_Cartage_Delivery_Date": null,
  "Delivery_Cartage_Advised_Date_Time": null,
  "Delivery_Cartage_Advised_Date": null,
  "Cartage_Deliver_By_Date_Time": null,
  "Cartage_Deliver_By_Date": null,
  "Cartage_Drop_Mode": "WUP",
  "Est_Cartage_Delivery_Date_Time": null,
  "Est_Cartage_Delivery_Date": null,
  "House_Bill_Type": "TUS",
  "Is_Active": "Y",
  "Total_Accrual_Recognized_Unrecognized": 0.0,
  "Total_Cost_Recognize_Unrecognized": -724.4,
  "Total_Expense_Recognize_Unrecognized_CST_ACR": -724.4,
  "Total_Income_Recognized_Unrecognized_REV_WIP": 1830.0,
  "Total_Revenue_Recognize_Unrecognized": 1830.0,
  "Total_Unrecognized_Expense_CST_ACR": 0.0,
  "Total_Unrecognized_Income_REV_WIP": 0.0,
  "Total_WIP_Recognized_Unrecognized": 0.0,
  "Unrecognized_Accrual": 0.0,
  "Unrecognized_Cost": 0.0,
  "Unrecognized_Revenue": 0,
  "Unrecognized_WIP": 0.0,
  "Actual_Pickup_Date_Time": null,
  "Actual_Pickup_Date": null,
  "Pickup_Cartage_Advised_Date_Time": null,
  "Pickup_Cartage_Advised_Date": null,
  "Cartage_Pickup_Mode": "WUP",
  "Interim_Receipt": null,
  "Interim_Receipt_No": null,
  "Pickup_By_Date_Time": null,
  "Pickup_By_Date": null,
  "Pickup_From_Date_Time": null,
  "Pickup_From_Date": null,
  "Last_edited_Date": null,
  "Imported_On": "2024-12-15",
  "Updated_On": null,
  "Source": null,
  "Controlling_Rep": null
}